In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
df = pd.read_csv(r'linear_regression\placement (1).csv')
df

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57
...,...,...
195,6.93,2.46
196,5.89,2.57
197,7.21,3.24
198,7.63,3.96


In [30]:
X= df.iloc[:,0:1]
y= df.iloc[:,1:]

In [ ]:
class GRADEINT_DESCENT:

    def __init__(self, learning_rate, epochs, int_m, int_b):
        self.m = int_m
        self.b = int_b
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):

        n = len(X_train)

        for i in range(self.epochs):

            y_pred = self.m * X_train.ravel() + self.b

            slope_gd = (-2/n) * np.sum((y_train - y_pred) * X_train.ravel())

            intercept_gd = (-2/n) * np.sum(y_train - y_pred)

            self.m = self.m - self.lr * slope_gd
            self.b = self.b - self.lr * intercept_gd

        print(self.m, self.b)

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train, y_test = train_test_split(X, y,
                                                      test_size=0.2,
                                                      random_state=42)

In [42]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()

X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

In [72]:
gd = GRADEINT_DESCENT(0.003,1000,0,205)

In [73]:
X_train = np.array(X_train).ravel()
y_train = np.array(y_train).ravel()

In [74]:
gd.fit(X_train, y_train)

0.6226971159414689 3.4876253020008496


In [75]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [78]:
lr.fit(X_train, y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.1606486   0.1882475   1.48539583 -0.43732758 -1.73447591 -0.06934224
  0.1330497   0.43663761 -1.98286601  0.55623284 -1.07210229 -0.23493564
  0.81382258 -1.00770486  0.1054508   1.31980243  0.83222185  0.62982991
 -0.06934224  0.09625117  2.12017054 -0.94330742  1.00701489  1.7797841
 -0.12454004  0.3538409  -0.97090632  1.01621452  0.09625117 -1.25609496
  2.07417238 -0.20733674 -1.35729093 -0.10614077  0.36304054 -0.0601426
  1.20020719  0.16984823  0.86902038 -1.4584869   0.74942515  1.82578227
 -0.86051072 -0.68571768  0.25264494 -2.03806381  0.2710442  -0.93410779
 -0.75011512 -1.4032891  -0.79611329 -0.22573601 -0.27173418 -0.60292098
 -0.36373051  0.81382258  1.56819253 -0.25333491 -1.4584869  -1.63327994
 -0.0601426  -0.04174334 -0.06934224 -1.07210229  0.70342698 -0.76851439
 -1.55048324 -0.61212062  1.4485973  -0.86051072  1.46699656 -0.10614077
  0.57463211  0.85982075 -1.11810046 -1.75287517  0.326242   -1.76207481
  1.77058447 -0.98010596  2.18456798  0.69422735 -0.02334407  0.34464127
  0.25264494 -0.75011512  0.80462295 -1.2376957  -0.83291182  0.39063944
  1.51299473 -1.07210229 -1.08130193  0.06865227  0.60223101  0.83222185
  0.38143981 -0.31773234 -0.49252538 -0.87890999 -0.75011512  1.05301305
 -0.63971952  1.71538667  0.57463211  0.30784274 -0.23493564  1.08061195
 -0.72251622  1.31980243 -0.65811878  1.11741049 -0.53852355 -0.84211145
 -0.06934224  0.51023467  0.92421818 -0.58452172 -1.49528544  0.71262661
  0.03185373  0.17904787  1.03461379  0.25264494  1.98217604 -0.13373967
 -0.62132025  2.36856065 -1.02610413 -0.07854187  1.49459546 -2.09326162
 -0.14293931 -0.37293014  0.11465043  1.14500939  0.26184457 -1.01690449
 -0.49252538 -2.24045575 -1.73447591  1.25540499  1.17260829 -0.29933308
 -0.81451255  0.04105336 -0.36373051  1.87178044  0.99781525 -0.14293931
 -0.46492648 -0.72251622  0.25264494  0.31704237  0.42743797 -0.80531292
  0.66662845  0.82302222  0.12385007 -1.72527627].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [48]:
lr.coef_

array([[0.62421668]])

In [49]:
lr.intercept_

array([2.995875])

### BATCH GRADIENT DESCENT ON MULTIVARIATE DATA


In [79]:
import numpy as np
import pandas as pd

In [80]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from  sklearn.model_selection import train_test_split

In [81]:
X, y = load_diabetes(return_X_y=True)

In [82]:
print( "shape of x" ,X.shape)
print("y shape ",y.shape)


shape of x (442, 10)
y shape  (442,)


In [ ]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [86]:
X_train , X_test , y_train, y_test = train_test_split(X,y,
                                                      test_size = 0.2,
                                                      random_state=42)

In [87]:
X_train.shape

(353, 10)

In [88]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.predict(X_test)


array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [89]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [90]:
lr.intercept_

np.float64(151.34560453985995)

### BUILDING FROM SCRATCH

In [102]:
class  GRAD_DESC():
    
    def __init__(self, learning_rate, epochs) :
        self.intercept =None
        self.coef = None
        self.lr = learning_rate
        self.epochs =epochs
        
    def fit(self,X_train, y_train):
        n = X_train.shape[0]
        self.intercept = 0
        self.coef = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
                  
            
            y_hat = self.intercept + np.dot(X_train , self.coef)
            
            intercept_drbt = -2 * np.sum(y_train - y_hat)/n
            
            coef_drbt =-2 * (np.dot(y_train-y_hat, X_train))/n
            
            self.intercept = self.intercept - self.lr * intercept_drbt

            self.coef = self.coef - self.lr * coef_drbt
            
        print("value of intercept ", self.intercept)
        print("value of coef", self.coef)
            
    def predict(self , X_test):
        return  self.intercept + np.dot( X_test, self.coef)
            

In [94]:
y_train[1]

np.float64(150.0)

In [ ]:
coef = np.ones(X_train.shape[1])
coef.shape

(11,)

In [111]:
lr =GRAD_DESC(0.001, 1000000)

In [112]:
lr.fit(X_train, y_train)

value of intercept  151.30379373285336
value of coef [  39.93596805 -236.67979986  550.34000615  340.32365392  -98.33761906
 -126.99925977 -215.57925686  149.13650531  411.11798803   71.82702252]


### STOCHASTIC GRADIENT DESCENTTTTTTTTTTTTTTTTT

In [1]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0,X_train.shape[0])
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_